const teamData = [{
    name: "Pratyush Mallick",
    position: "Co-Founder & Director of Innovation",
    instagram: "https://www.instagram.com/pmallick_/",
    linkedin: "https://www.linkedin.com/in/pratyush-m-993645186/",
    email: "mailto:pratyushmallick@outlook.com",
  },
  {
    name: "Mylinh Murphree",
    position: "Co-Founder & Director of Operations",
    instagram: "https://www.instagram.com/mylinh_m/",
    linkedin: "",
    email: "mailto:mmylinh.murphree@gmail.com",
  },
  {
    name: "Nila Jeyapriya",
    position: "Director of Development",
    instagram: "https://www.instagram.com/nila.jeyapriya/",
    linkedin: "https://www.linkedin.com/in/nilajeyapriya/",
    email: "mailto:nilajeyapriya@gmail.com",
  },
  {
    name: "Rohit Rajan",
    position: "Director of Systems Architecture",
    instagram: "https://www.instagram.com/rajansrohit/",
    linkedin: "https://www.linkedin.com/in/rajansrohit/",
    email: "mailto:rohitrajan.cs@gmail.com",
  },
  {
    name: "Ethan Davenport",
    position: "Director of Finance",
    instagram: "https://www.instagram.com/ethandav_04/",
    linkedin: "",
    email: "mailto:ethandavenport@att.net",
  },
  {
    name: "Yemisi Badmus",
    position: "Director of Marketing",
    instagram: "https://www.instagram.com/yemisi_o_badmus/",
    linkedin: "https://www.linkedin.com/in/yemisi-badmus-687b0b146/",
    email: "mailto:yemisi.badmus1@gmail.com",
  },
  {
    name: "Shrey Joshi",
    position: "Web Development Lead",
    instagram: "https://www.instagram.com/shreyj1729/",
    linkedin: "https://www.linkedin.com/in/shrey-joshi-005623194/",
    email: "mailto:shreyjoshi2004@gmail.com",
  },
  {
    name: "Brian Vo",
    position: "SEO Lead",
    instagram: "https://www.instagram.com/brianhvo/",
    linkedin: "https://www.linkedin.com/in/brian-vo-827564189/",
    email: "mailto:brianhvo0@gmail.com",
  },
  {
    name: "Anay Gupta",
    position: "Development Lead",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/anay-gupta-355028176/",
    email: "mailto:",
  },
  {
    name: "Cynthia Diep",
    position: "Social Media Lead",
    instagram: "https://www.instagram.com/cynthiadiep/",
    linkedin: "http://linkedin.com/in/cynthia-diep-4420351aa",
    email: "mailto:cynthia.diep1203@gmail.com",
  },
  {
    name: "Ishaan Javali",
    position: "Developer",
    instagram: "https://www.instagram.com/ij_apps/",
    linkedin: "https://www.linkedin.com/in/ishaan-javali-b2602018b/",
    email: "mailto:ishaanjav@gmail.com",
  },
  {
    name: "Rohan Ganta",
    position: "Developer",
    instagram: "",
    linkedin: "",
    email: "mailto:",
  },
  {
    name: "Sophia Khan",
    position: "Product Designer",
    instagram: "https://www.instagram.com/sophiamkhan/",
    linkedin: "https://www.linkedin.com/in/sophia-m-khan-9b119a1a9/",
    email: "mailto:smk_1000@hotmail.com",
  },
  {
    name: "Navi Lanka",
    position: "Marketing Producer",
    instagram: "https://www.instagram.com/wingsnavi_/",
    linkedin: "https://www.linkedin.com/in/jahnavi-lanka-a37633185/",
    email: "mailto:",
  },
  {
    name: "Hardik Singh",
    position: "Outreach",
    instagram: "https://www.instagram.com/hardsingh17/",
    linkedin: "https://www.linkedin.com/in/hardik-singh-9043771aa/",
    email: "mailto:hardik.hs.singh@gmail.com",
  },
  {
    name: "Dhanush Jain",
    position: "Outreach",
    instagram: "https://www.instagram.com/dhaaanush_jain/",
    linkedin: "http://linkedin.com/in/dhanush-jain-93437b1aa",
    email: "mailto:",
  },
  {
    name: "Tim Murphree",
    position: "Technical Advisor",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/timmurphree/",
    email: "mailto:tim@timmurphree.com",
  },
];


export default teamData;